N = int(input())
print("The next number for the number", end=' ')
print(N, end=' is ')
print(N + 1, end='')
print('.')
print("The previous number for the number", end=' ')
print(N, end=' is ')
print(N-1, end='.')