a = float(input())
b = float(input())
c = float(input())
d = float(input())
e = float(input())
f = float(input())
x = (-e * d + b * f) / (-a * d + b * c)
y = (a * f - e * c) / (d * a - b * c)
print(x, y)
