CREATE TABLE basket ( image TEXT,
	name TEXT,
	qty INTEGER,
	price REAL,
	subTotal REAL,
	id INTEGER PRIMARY KEY NOT NULL UNIQUE
);

CREATE TABLE customers (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	username TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL,
	fname TEXT NOT NULL,
	lname TEXT NOT NULL,
	email TEXT NOT NULL UNIQUE,
	address TEXT NOT NULL
);

CREATE TABLE products (
	Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	Name TEXT NOT NULL,
	Image TEXT NOT NULL,
	Price REAL NOT NULL,
	onSale INTEGER,
	onSalePrice REAL,
	kind  TEXT NOT NULL,
	category TEXT NOT NULL,
	description TEXT
);

CREATE TABLE purchases ( uid TEXT,
	name TEXT,
	image TEXT,
	quantity INTEGER,
	id INTEGER,
	date DATE NOT NULL DEFAULT CURRENT_DATE, status BOOLEAN DEFAULT (False)
);

CREATE TABLE checkout (
	checkout_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	delivery_price INTEGER NOT NULL,
	Delivery_adress TEXT NOT NULL,
	Payment_method TEXT NOT NULL,
	Pick_up_point TEXT
);
